version: "3.0"

services:
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks: 
       - local-net
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks: 
      - local-net

  api:
    links:
      - mongo
      - mongo-express
    container_name: "web"
    build: .
    restart: always
    ports:
       - 8000:8000
    networks: 
      - local-net

networks:
  local-net:
      driver: bridge
      
      
